name: Build Linux Kernel

on:
  workflow_dispatch:

jobs:
  BuildThisShitIHateThis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Config
      uses: actions/checkout@v4
      
    - name: Restore Compiler Cache
      id: ccache-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.cache/ccache
        key: kernel-ccache-${{ github.sha }}
        restore-keys: |
          kernel-ccache-

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc git ccache gawk findutils diffutils

    - name: Download Kernel Source
      run: |
        wget https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-7.0.11.tar.xz
        tar -xf linux-7.0.11.tar.xz

    - name: Prepare Configuration
      env:
        SIGNING_KEY_DATA: ${{ secrets.KERNEL_SIGNING_KEY }}
      run: |
        # Get the Alpine 3.23
        #mv .config linux-7.0.11/.config
        cd linux-7.0.11

        # Or else, build the default
        make defconfig
        
        cat << 'EOF' > certs/my_custom_key.pem
        $SIGNING_KEY_DATA
        EOF
        
        chmod 600 certs/my_custom_key.pem
        
        ./scripts/config --set-str CONFIG_MODULE_SIG_KEY "certs/my_custom_key.pem"
        
        ./scripts/config --set-str CONFIG_SYSTEM_TRUSTED_KEYS ""
        ./scripts/config --set-str CONFIG_SYSTEM_REVOCATION_KEYS ""
        ./scripts/config --set-str LOCALVERSION "-drmpanic"

        ./scripts/config --enable CONFIG_BLOCK
        ./scripts/config --enable CONFIG_BLK_DEV_SD
        ./scripts/config --enable CONFIG_SCSI
        ./scripts/config --enable CONFIG_EXT4_FS
        
        ./scripts/config --enable CONFIG_DRM_PANIC
        ./scripts/config --enable CONFIG_DRM_PANIC_SCREEN
        ./scripts/config --enable CONFIG_DRM_PANIC_SCREEN_QR_CODE
        ./scripts/config --disable CONFIG_GCC_PLUGINS
        
        make olddefconfig

    - name: Compile Kernel and Modules
      run: |
        cd linux-7.0.11
        
        export CCACHE_DIR=~/.cache/ccache
        export CCACHE_MAXSIZE=10G
 
        ccache -z
        make -j$(nproc --ignore=1) CC="ccache gcc"
        ccache -s

    - name: Save Compiler Cache (Always)
      uses: actions/cache/save@v4
      if: always() && steps.ccache-restore.outputs.cache-hit != 'true'
      with:
        path: ~/.cache/ccache
        key: kernel-ccache-${{ github.sha }}

    - name: Create Artifact Directory
      run: |
        mkdir artifacts
        KERNEL_RELEASE=$(make -C linux-7.0.11 -s kernelrelease)
        
        cp linux-7.0.11/arch/x86/boot/bzImage artifacts/vmlinuz-$KERNEL_RELEASE
        cp linux-7.0.11/System.map artifacts/System.map-$KERNEL_RELEASE
        cp linux-7.0.11/.config artifacts/config-$KERNEL_RELEASE
        
        cd linux-7.0.11
        sudo make modules_install INSTALL_MOD_PATH=../artifacts/modules_root
        cd ../artifacts
        sudo tar -czf modules.tar.gz modules_root/
        sudo rm -rf modules_root/
        
    - name: Upload Artifacts to HFS Web Server
      env:
        HFS_URL: "https://fkrystal.qzz.io/LinuxKernel"
        CF_TRIGGER: ${{ secrets.CF_TRIGGER }}
        HFS_USER: ${{ secrets.HFS_USER }}
        HFS_PASS: ${{ secrets.HFS_PASS }}
      run: |
        cd linux-7.0.11
        FOLDER_NAME="$(make -s kernelrelease)-$(TZ='Asia/Ho_Chi_Minh' date +'%Y%m%d-%H%M%S')"
        cd ..
        
        BASE_URL=$(echo "$HFS_URL" | sed -e 's/\(https*:\/\/[^\/]*\).*/\1/')
        VFS_PATH=$(echo "$HFS_URL" | sed -e 's/https*:\/\/[^\/]*//')
        if [ -z "$VFS_PATH" ]; then VFS_PATH="/"; fi
        
        curl -X POST -u "$HFS_USER:$HFS_PASS" \
             -H "Content-Type: application/json" \
             -H "$CF_TRIGGER: 1" \
             -H "x-hfs-anti-csrf: 1" \
             -d "{\"uri\":\"$VFS_PATH\",\"name\":\"$FOLDER_NAME\"}" \
             "$BASE_URL/~/api/create_folder"
             
        TARGET_URL="$BASE_URL$VFS_PATH/$FOLDER_NAME/"
        echo -e "\nUploading artifacts to destination path: $TARGET_URL\n"
        
        for file in artifacts/*; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            echo "Uploading $filename..."
            
            curl -X POST -u "$HFS_USER:$HFS_PASS" \
                 -H "$CF_TRIGGER: 1" \
                 -F "file=@$file" \
                 "$TARGET_URL"
            
            echo -e "\nFinished $filename\n"
          fi
        done
        

    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: custom-kernel-7.0.11
        path: artifacts/
        retention-days: 5
